name: Build bundle workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get content from git
        uses: actions/checkout@v2
      - name: setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: build bundle
        run: |
          cd build-common
          python3 bundle.py -b $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
          cd ..
      - name: upload bundle
      - uses: actions/upload-artifact@v3
        with:
          name: cat-printer-bare-bundle.zip
          path: cat-printer-bare-*.zip
      


      