name: Build bundle workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: get repo contents
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"