name: Build bundle workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get content from git
        uses: actions/checkout@v2
      - name: setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      